-- 1. Create the Environment
USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE DATABASE ECO_PROJECT;
CREATE OR REPLACE SCHEMA ECO_PROJECT.PUBLIC;

-- 2. Create the Table
CREATE OR REPLACE TABLE ECO_PROJECT.PUBLIC.LOGISTICS_DATA (
    SHIPMENT_ID STRING,
    DISTANCE_KM FLOAT,
    LOAD_TONS FLOAT,
    VEHICLE_TYPE STRING,
    ROUTE_PATH STRING
);

-- 3. Insert Demo Data
INSERT INTO ECO_PROJECT.PUBLIC.LOGISTICS_DATA 
VALUES ('402', 1200.5, 15.0, 'TRUCK', 'SF to Denver via I-80');

-- 4. Grant Permissions to the App Role (ACCOUNTADMIN)
GRANT USAGE ON DATABASE ECO_PROJECT TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA ECO_PROJECT.PUBLIC TO ROLE ACCOUNTADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA ECO_PROJECT.PUBLIC TO ROLE ACCOUNTADMIN;

-- 5. Grant Warehouse usage (Ensure this matches your warehouse name)
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ACCOUNTADMIN;

-- Verify
SELECT * FROM ECO_PROJECT.PUBLIC.LOGISTICS_DATA;